// Generated by research/export-site-data.mjs from research/closed-market.json — do not hand-edit.
export const MEASURED = {
  "generated": "2026-09-23T23:19:57.834Z",
  "window": {
    "from": "2026-08-31T13:30:00Z",
    "to": "2026-09-21T13:30:00Z",
    "fromBlock": 50901278,
    "toBlock": 68833663,
    "days": 21,
    "closedTimePct": 81.94,
    "closedPeriods": 14,
    "weekendHolidayPeriods": 3
  },
  "stocks": 195,
  "pools": {
    "ever": 84546,
    "dynamicAll": 51470,
    "censusActive": 5320
  },
  "census": {
    "swaps": 6347865,
    "swapsClosedPct": 72.69,
    "usd": 1777959201,
    "usdClosed": 1289297140,
    "usdClosedPct": 72.52,
    "hooklessUsdClosedPct": 69.72
  },
  "other": {
    "estSwaps": 24412277,
    "estSwapsClosedPct": 73.43,
    "sampledPct": 2.01
  },
  "drift": {
    "stocks": 77,
    "all": {
      "n": 578,
      "medianPct": 1.5,
      "p90Pct": 4.92,
      "maxPct": 150.12,
      "over1Pct": 380,
      "over5Pct": 57,
      "over10Pct": 18
    },
    "weekend": {
      "n": 148,
      "medianPct": 2.36,
      "p90Pct": 8.71,
      "maxPct": 150.12,
      "over1Pct": 116,
      "over5Pct": 31,
      "over10Pct": 10
    },
    "weeknight": {
      "n": 430,
      "medianPct": 1.29,
      "p90Pct": 3.87,
      "maxPct": 47.35,
      "over1Pct": 264,
      "over5Pct": 26,
      "over10Pct": 8
    },
    "histWeeknight": [
      {
        "label": "<0.5%",
        "n": 72
      },
      {
        "label": "0.5–1%",
        "n": 94
      },
      {
        "label": "1–2%",
        "n": 124
      },
      {
        "label": "2–5%",
        "n": 114
      },
      {
        "label": "5–10%",
        "n": 18
      },
      {
        "label": "≥10%",
        "n": 8
      }
    ],
    "histWeekend": [
      {
        "label": "<0.5%",
        "n": 11
      },
      {
        "label": "0.5–1%",
        "n": 21
      },
      {
        "label": "1–2%",
        "n": 34
      },
      {
        "label": "2–5%",
        "n": 51
      },
      {
        "label": "5–10%",
        "n": 21
      },
      {
        "label": "≥10%",
        "n": 10
      }
    ],
    "nyseMedianGapPct": 1.01,
    "nyseP90GapPct": 3.22
  },
  "vsNyse": {
    "preCloseMedianPct": 0.41,
    "closedMedianPct": 1.42,
    "closedP90Pct": 5.37,
    "weekendP90Pct": 8.57
  },
  "fees": {
    "openPct": 0.5288,
    "closedPct": 0.5727
  },
  "worst": {
    "ticker": "GLXY",
    "periodKind": "weekend/holiday",
    "closedFrom": "Fri 2026-09-11 16:00 ET",
    "closedTo": "Mon 2026-09-14 09:30 ET",
    "maxDevPct": 150.12,
    "anchorUsd": 25.0818,
    "worstUsd": 62.7355,
    "worstAt": "Sun 2026-09-13 11:18 ET",
    "nyseLastClose": 24.4,
    "usdInPeriod": 1016279
  }
};
